In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("C:\\Users\\e006697\\Documents\\Python_2\\CursoPython\\Python Data Science\\Fuentes Kike\\Base de datos\\base_datos_2008.csv",nrows=100000)

In [3]:
np.corrcoef(df["ArrDelay"],df["DepDelay"]) #Funcion de NumPy que da el coeficiente de correlación. No admiete valores faltantes NaN.

array([[nan, nan],
       [nan, nan]])

In [4]:
df.dropna(inplace=True, subset=["ArrDelay","DepDelay"]) #Eliminamos los registros con valores NaN en las 2 columnas que queremos analizar. Lo hacemos en el mismo data frame, con el inplace=True

In [5]:
np.corrcoef(df["ArrDelay"],df["DepDelay"]) #Funcion de NumPy que da el cociente de correlación. 
#Todo lo que supera 0.7 se considera muy correlacionado. En este caso, es 0.94, por lo que parecen estar muy correlacionadas

array([[1.       , 0.9422735],
       [0.9422735, 1.       ]])

In [7]:
np.corrcoef([df["ArrDelay"],df["DepDelay"],df["DepTime"]]) #Se puede hacer el estudio con mas columnas

array([[1.        , 0.9422735 , 0.23241529],
       [0.9422735 , 1.        , 0.25725889],
       [0.23241529, 0.25725889, 1.        ]])

In [3]:
#Podemos obtener una relacion de toda la correlación que hay entre todas las columnas del data frame. Para eso, primero tenemos que eliminar las variables no numericas
df.drop(inplace=True, columns=["Year","Cancelled","Diverted"])

In [4]:
df.corr()
#devuelve la correlacion una a una

Month  DayofMonth  DayOfWeek   DepTime  CRSDepTime  \
Month                NaN         NaN        NaN       NaN         NaN   
DayofMonth           NaN    1.000000  -0.119195 -0.001222    0.005302   
DayOfWeek            NaN   -0.119195   1.000000  0.031130    0.024901   
DepTime              NaN   -0.001222   0.031130  1.000000    0.985475   
CRSDepTime           NaN    0.005302   0.024901  0.985475    1.000000   
ArrTime              NaN   -0.004445   0.021947  0.796903    0.795609   
CRSArrTime           NaN   -0.000960   0.028391  0.852065    0.862598   
FlightNum            NaN    0.072934  -0.039755  0.023330    0.023253   
ActualElapsedTime    NaN    0.004568   0.015945 -0.069542   -0.074644   
CRSElapsedTime       NaN   -0.005462   0.016669 -0.066037   -0.069734   
AirTime              NaN    0.000893   0.014324 -0.065054   -0.069232   
ArrDelay             NaN    0.027501   0.085299  0.232415    0.180684   
DepDelay             NaN    0.007096   0.098305  0.257592    0.201836   
Distance             NaN   -0.005199   0.016547 -0.057003   -0.060746   
TaxiIn               NaN   -0.012618   0.034878  0.029098    0.024048   
TaxiOut              NaN    0.040736   0.000343 -0.068125   -0.075015   
CarrierDelay         NaN   -0.061650   0.031015  0.029925   -0.015536   
WeatherDelay         NaN    0.055178   0.008769 -0.018628   -0.057462   
NASDelay             NaN    0.111780   0.001660 -0.128269   -0.149643   
SecurityDelay        NaN   -0.012357   0.024726 -0.022763   -0.025722   
LateAircraftDelay    NaN    0.079725   0.079787  0.229938    0.227241   

                    ArrTime  CRSArrTime  FlightNum  ActualElapsedTime  \
Month                   NaN         NaN        NaN                NaN   
DayofMonth        -0.004445   -0.000960   0.072934           0.004568   
DayOfWeek          0.021947    0.028391  -0.039755           0.015945   
DepTime            0.796903    0.852065   0.023330          -0.069542   
CRSDepTime         0.795609    0.862598   0.023253          -0.074644   
ArrTime            1.000000    0.887002   0.011193           0.013706   
CRSArrTime         0.887002    1.000000   0.014096           0.025615   
FlightNum          0.011193    0.014096   1.000000           0.024159   
ActualElapsedTime  0.013706    0.025615   0.024159           1.000000   
CRSElapsedTime     0.016936    0.032189   0.025818           0.983501   
AirTime            0.018445    0.030644   0.021619           0.992457   
ArrDelay           0.076353    0.142571  -0.001017          -0.013101   
DepDelay           0.091164    0.170809   0.003004           0.020641   
Distance           0.024675    0.042508   0.017957           0.963610   
TaxiIn             0.044000    0.042752   0.007277           0.183375   
TaxiOut           -0.062210   -0.061671   0.023691           0.167747   
CarrierDelay      -0.027949   -0.004882  -0.020801           0.021032   
WeatherDelay      -0.033068   -0.049083   0.004887           0.039746   
NASDelay          -0.067516   -0.119460   0.002978           0.208190   
SecurityDelay     -0.005993   -0.016722  -0.007659           0.014323   
LateAircraftDelay -0.050018    0.171666  -0.002957          -0.076740   

                   CRSElapsedTime  ...  ArrDelay  DepDelay  Distance  \
Month                         NaN  ...       NaN       NaN       NaN   
DayofMonth              -0.005462  ...  0.027501  0.007096 -0.005199   
DayOfWeek                0.016669  ...  0.085299  0.098305  0.016547   
DepTime                 -0.066037  ...  0.232415  0.257592 -0.057003   
CRSDepTime              -0.069734  ...  0.180684  0.201836 -0.060746   
ArrTime                  0.016936  ...  0.076353  0.091164  0.024675   
CRSArrTime               0.032189  ...  0.142571  0.170809  0.042508   
FlightNum                0.025818  ... -0.001017  0.003004  0.017957   
ActualElapsedTime        0.983501  ... -0.013101  0.020641  0.963610   
CRSElapsedTime           1.000000  ... -0.088450  0.003649  0.979855   
AirTime      

In [5]:
#Para ver graficamente la correlación.
df.drop(inplace=True, columns=["Month"]) #Elimnamos month, ya que no lo sabe interpretar.
corr = round(df.corr(),3) #Redondeo a 3 decimales
corr.style.background_gradient() #mostrar degradado según la intensidad de la correlación