In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("C:\\Users\\e006697\\Documents\\Python_2\\CursoPython\\Python Data Science\\Fuentes Kike\\Base de datos\\base_datos_2008.csv",nrows=100000)

In [3]:
np.corrcoef(df["ArrDelay"],df["DepDelay"]) #Funcion de NumPy que da el cociente de correlación. No admiete valores faltantes NaN.

array([[nan, nan],
       [nan, nan]])

In [4]:
df.dropna(inplace=True, subset=["ArrDelay","DepDelay"]) #Eliminamos los registros con valores NaN en las 2 columnas que queremos analizar. Lo hacemos en el mismo data frame, con el inplace=True

In [5]:
np.corrcoef(df["ArrDelay"],df["DepDelay"]) #Funcion de NumPy que da el cociente de correlación. 
#Todo lo que supera 0.7 se considera muy correlacionado. En este caso, es 0.94, por lo que parecen estar muy correlacionadas

array([[1.       , 0.9422735],
       [0.9422735, 1.       ]])

In [7]:
np.corrcoef([df["ArrDelay"],df["DepDelay"],df["DepTime"]]) #Se puede hacer el estidio con mas columnas

array([[1.        , 0.9422735 , 0.23241529],
       [0.9422735 , 1.        , 0.25725889],
       [0.23241529, 0.25725889, 1.        ]])