In [1]:
import numpy as np

In [2]:
#Crear un array
valoraciones = np.array([[8,7,8,5],[2,6,8,1],[8,8,9,5]])
valoraciones

array([[8, 7, 8, 5],
       [2, 6, 8, 1],
       [8, 8, 9, 5]])

In [3]:
valoraciones[0][1] #acceso a la información. EN esta caso, primera dimension son filas, segunda dimensión, son columnas. Si el objeto tuviera mas de dos dimensiones, se añadirian mas []

7

In [4]:
valoraciones [0,1] #Otra forma de acceder a la misma información. Si el objeto tuviera mas de dos dimensiones, se añadirian mas valores entre los [,]

7

In [5]:
valoraciones2 = np.array([[[8,7,8,5],[2,6,8,1]],[[8,8,9,5],[8,7,6,5]],[[10,9,5,3],[5,7,2,5]]]) #creamos array de 3 dimensiones

In [6]:
valoraciones2 #Por ejemplo, 3 clietes, que valoran 4 productos en AA y el AC

array([[[ 8,  7,  8,  5],
        [ 2,  6,  8,  1]],

       [[ 8,  8,  9,  5],
        [ 8,  7,  6,  5]],

       [[10,  9,  5,  3],
        [ 5,  7,  2,  5]]])

In [7]:
valoraciones2[0,1,2] #Cliente 1 (el 0 es la pimera occurrencia). Datos de AC, Valoración del producto 3

8

In [8]:
np.zeros((3,2,4)) #Crear array con valores 0

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [9]:
valoraciones2 + np.ones((3,2,4)) #Creamos un array de valores 1, con las mismas dimensiones que valoraciones 2, y realizamos una operación entre los 2 objetos, en este caso, una suma

array([[[ 9.,  8.,  9.,  6.],
        [ 3.,  7.,  9.,  2.]],

       [[ 9.,  9., 10.,  6.],
        [ 9.,  8.,  7.,  6.]],

       [[11., 10.,  6.,  4.],
        [ 6.,  8.,  3.,  6.]]])

In [10]:
np.mean(valoraciones2) #media de todos los valores del array

6.125

In [11]:
np.mean(valoraciones2,axis = 0) #axis = 0, indica que queremos las medias por la primera dimensión

array([[8.66666667, 8.        , 7.33333333, 4.33333333],
       [5.        , 6.66666667, 5.33333333, 3.66666667]])

In [12]:
np.mean(valoraciones2,axis = 1)

array([[5. , 6.5, 8. , 3. ],
       [8. , 7.5, 7.5, 5. ],
       [7.5, 8. , 3.5, 4. ]])

In [14]:
np.reshape([1,2,3,4,5,6,7,8,9,10,11,12],(3,2,2)) #reshape es una función que pasa una lista a un array con las dimensiones que le indiquemos

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])